site_name: 自分用の英文法まとめ

theme:
  name: material
  custom_dir: src/overrides
  features:
    - navigation.tabs
  favicon: favicon.ico
  icon:
    logo: material/library
  palette:
    primary: indigo
    accent: indigo

plugins:
  - search:
      lang: ja

extra_css:
  - assets/stylesheets/custom.css

extra_javascript:
  - assets/javascripts/custom.js

markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  # - pymdownx.highlight:
  #     linenums: true

nav:
  - 索引: index.md
  - 語順の基本:
    - Introduction: word-order/introduction.md
  - 動詞:
    - Introduction: varb/introduction.md
    - 動詞1: varb/1.md
    - 動詞2: varb/2.md
  - 時制:
    - Introduction: tense/introduction.md
    - 時制1: tense/1.md
    - 時制2: tense/2.md
    - 時制3: tense/3.md
    - 時制4: tense/4.md
    - 時制5: tense/5.md
  - 助動詞:
    - Introduction: auxiliary-varb/introduction.md
    - 助動詞1: auxiliary-varb/1.md
    - 助動詞2: auxiliary-varb/2.md
    - 助動詞3: auxiliary-varb/3.md
  - 名詞と冠詞:
    - Introduction: noun-article/introduction.md
  - 形容詞:
    - Introduction: adjective/introduction.md
  - 代名詞:
    - Introduction: pronoun/introduction.md
  - 副詞:
    - Introduction: adverb/introduction.md
  - 不定詞:
    - Introduction: infinitive/introduction.md
  - 動名詞:
    - Introduction: gerund/introduction.md
  - 分詞:
    - Introduction: participle/introduction.md
  - 受動態:
    - Introduction: passive-voice/introduction.md
  - 疑問詞:
    - Introduction: interrogative/introduction.md
  - 比較:
    - Introduction: comparison/introduction.md
  - 接続詞:
    - Introduction: conjunction/introduction.md
  - 仮定法:
    - Introduction: subjunctive-mood/introduction.md
  - 関係詞:
    - Introduction: relatives/introduction.md
  - 前置詞:
    - Introduction: preposition/introduction.md
